"""Crear tabla rentals y relaciones

Revision ID: 2fdf3053cac2
Revises: 99e084076015
Create Date: 2026-08-01 21:07:25.606204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fdf3053cac2'
down_revision: Union[str, Sequence[str], None] = '99e084076015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    op.add_column('bikes', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('bikes', sa.Column('model', sa.String(), nullable=True))
    op.add_column('bikes', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('bikes', sa.Column('price_per_hour', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_bikes_station_id'), table_name='bikes')
    op.create_index(op.f('ix_bikes_brand'), 'bikes', ['brand'], unique=False)
    op.drop_column('bikes', 'status')
    op.drop_column('bikes', 'station_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bikes', sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bikes', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bikes_brand'), table_name='bikes')
    op.create_index(op.f('ix_bikes_station_id'), 'bikes', ['station_id'], unique=False)
    op.drop_column('bikes', 'price_per_hour')
    op.drop_column('bikes', 'is_available')
    op.drop_column('bikes', 'model')
    op.drop_column('bikes', 'brand')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
